application: gencrowd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

handlers:

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /css
  static_dir: css

- url: /eval.*
  script: handlers.evaluate.app

- url: /api.*
  script: handlers.api.app

- url: /.*
  script: handlers.main.app
